In [1]:
# Imports
import IPython
import IPython.display
import pandas as pd
from numpy import mean
from numpy import std
import seaborn as sn
import matplotlib.pyplot as plt
import numpy as np
import glob
import tensorflow as tf
import math
import seaborn as sns
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split

np.random.seed(37151)
tf.random.set_seed(37151)

In [2]:
time = 2.0
steps = int(time * 200)

In [3]:
class LSTMClassification():
    def __init__(self):
         self.df = pd.read_csv('../master_df_normalized_108.csv')     
    
    # model_output_size = numero de categorias a determinar
    # mag_offset = valor magnitudeminimo a categorizar
    def prep_features(self, model_output_size=3, mag_offset=4, timedelta = 400):
        self.timedelta = timedelta
        self.model_output_size = model_output_size
        features = []
        labels = []
        for index, row in self.df.iterrows():
            try:
                records = row['list_records'].replace("'", '')
                records = records.replace('[', '')
                records = records.replace(']', '')                                  
                list_records = records.split(', ')
                magnitude = row['Mag']
                for record in list_records:
                    df_ts = pd.read_csv("../Renamed_Records/" + record, index_col=None, header=0, dtype=np.float32)
                    features.append(df_ts.iloc[:timedelta].to_numpy(dtype='float'))
                    labels.append(np.eye(model_output_size)[magnitude-mag_offset])
            except:
                continue
        self.features=np.array(features)
        self.labels=np.array(labels)
    
    def split_dataset(self, split = 0.8):
        self.trainX, self.testX, self.trainY, self.testY = train_test_split(self.features, self.labels, test_size = split, shuffle = True)
        print(self.trainX)
        print(self.trainY)
    
    def create_model(self, height=-1, width=2, model_output_size=-1):
        model = Sequential()
        if height == -1:
            height = self.timedelta
            
        if model_output_size == -1:
            model_output_size = self.model_output_size

        # input shape = num timesteps, num features(temp, acc.)
        model.add(LSTM(100, input_shape = (height, width)))
        model.add(Dropout(0.5))
        model.add(Dense(100, activation = 'relu'))
        model.add(Dense(model_output_size, activation = 'softmax'))
        model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
        # Printing the models summary
        #model.summary()
        return model
    
    def evaluate_model(self, model, trainX, trainY, testX, testY, epochs=100, batch_size=3, verbose=0):
        history = model.fit(trainX, trainY, epochs=epochs, batch_size=batch_size, verbose=verbose)
        loss, accuracy = model.evaluate(testX, testY, batch_size, verbose=verbose)
        return accuracy
    
    def predict_model(self, model, data):
        features = data['Values'].to_numpy().astype(float)
        predictions = model.predict(features)
        return predictions

In [4]:
# 2 segundos

classifier = LSTMClassification()
classifier.prep_features(model_output_size=5, mag_offset=3, timedelta = 2*200)
print(classifier.features.shape)
print(classifier.labels.shape)

classifier.split_dataset()
# height = numero de timestamps, width (time, acc.)
LSTM_magnitude_model = classifier.create_model()

# struct: (Number or files, number of steps, number of columns)
# (70, 400, 2)
classifier.evaluate_model(LSTM_magnitude_model, classifier.trainX,  classifier.trainY,  classifier.testX,  classifier.testY, verbose=1)

(468, 400, 2)
(468, 5)
[[[ 0.00000000e+00  0.00000000e+00]
  [ 4.99999989e-03 -2.16179842e-07]
  [ 9.99999978e-03 -4.32359684e-07]
  ...
  [ 1.98500001e+00 -2.26376997e-07]
  [ 1.99000001e+00 -2.21278412e-07]
  [ 1.99500000e+00 -2.15160114e-07]]

 [[ 0.00000000e+00  0.00000000e+00]
  [ 4.99999989e-03  6.70463396e-06]
  [ 9.99999978e-03  1.34174261e-05]
  ...
  [ 1.98500001e+00  1.38711994e-05]
  [ 1.99000001e+00  9.89634555e-06]
  [ 1.99500000e+00  7.44688587e-05]]

 [[ 0.00000000e+00  0.00000000e+00]
  [ 4.99999989e-03  1.74555025e-05]
  [ 9.99999978e-03  3.48865324e-05]
  ...
  [ 1.98500001e+00  1.19714684e-06]
  [ 1.99000001e+00 -7.30830607e-06]
  [ 1.99500000e+00 -6.47213892e-06]]

 ...

 [[ 0.00000000e+00  0.00000000e+00]
  [ 4.99999989e-03 -2.35044581e-06]
  [ 9.99999978e-03 -4.70701025e-06]
  ...
  [ 1.98500001e+00 -2.34963009e-05]
  [ 1.99000001e+00 -2.39776073e-05]
  [ 1.99500000e+00 -2.57223419e-05]]

 [[ 0.00000000e+00  0.00000000e+00]
  [ 4.99999989e-03  6.11829742e-09]
  [

0.2133333384990692

In [5]:
# 4 segundos

classifier = LSTMClassification()
classifier.prep_features(model_output_size=5, mag_offset=3, timedelta = 4*200)
print(classifier.features.shape)
print(classifier.labels.shape)

classifier.split_dataset()
# height = numero de timestamps, width (time, acc.)
LSTM_magnitude_model = classifier.create_model()

# struct: (Number or files, number of steps, number of columns)
# (70, 400, 2)
classifier.evaluate_model(LSTM_magnitude_model, classifier.trainX,  classifier.trainY,  classifier.testX,  classifier.testY, verbose=1)

(468, 800, 2)
(468, 5)
[[[ 0.00000000e+00  0.00000000e+00]
  [ 4.99999989e-03  2.03943240e-09]
  [ 9.99999978e-03  4.07886480e-09]
  ...
  [ 3.98499990e+00 -3.71584588e-06]
  [ 3.99000001e+00 -3.90959212e-06]
  [ 3.99499989e+00  1.88953413e-06]]

 [[ 0.00000000e+00  0.00000000e+00]
  [ 4.99999989e-03 -5.91435416e-08]
  [ 9.99999978e-03 -1.17267362e-07]
  ...
  [ 3.98499990e+00  2.14833817e-05]
  [ 3.99000001e+00  1.76319136e-05]
  [ 3.99499989e+00  1.37824845e-05]]

 [[ 0.00000000e+00  0.00000000e+00]
  [ 4.99999989e-03 -6.18591439e-04]
  [ 9.99999978e-03 -1.23714423e-03]
  ...
  [ 3.98499990e+00 -3.06612346e-04]
  [ 3.99000001e+00 -2.99152103e-04]
  [ 3.99499989e+00 -2.91919248e-04]]

 ...

 [[ 0.00000000e+00  0.00000000e+00]
  [ 4.99999989e-03 -8.44182287e-05]
  [ 9.99999978e-03 -1.68817074e-04]
  ...
  [ 3.98499990e+00  2.68469856e-04]
  [ 3.99000001e+00  3.16991424e-03]
  [ 3.99499989e+00  5.22568263e-03]]

 [[ 0.00000000e+00  0.00000000e+00]
  [ 4.99999989e-03 -3.11819022e-05]
  [

0.2240000069141388